<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MSF" Id="{8220cde7-77d5-46ea-ad62-e04e0f05cd58}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK MSF

VAR_INPUT
	start  : BOOL;
	stop   : BOOL;
	emg    : BOOL;
	ack    : BOOL;
	fc1    : BOOL;
	fc2    : BOOL;
END_VAR

VAR_OUTPUT
	H1     : BOOL;
	HEMG   : BOOL;
	M      : BOOL;
	libero : BOOL;
END_VAR

VAR
	enable : BOOL;
	tr_S0_S1 : BOOL;
	tr_S1_S2 : BOOL;
	tr_S2_S3 : BOOL;
	tr_S3_S1 : BOOL;
	tr_S3_S0 : BOOL;
	tr_SE_SA : BOOL;
	tr_SA_S0 : BOOL;
	stato  : STATI := STATI.S0;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MSF">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>